[editors.normal]
primary   = 'hex'  # 'hex', 'bin', 'utf8'
secondary = 'utf8' # 'hex', 'bin', 'utf8'

[editors.diff]
primary   = 'hex' # 'hex', 'bin', 'utf8'
secondary = 'hex' # 'hex', 'bin', 'utf8'

# Column count is the number of columns per row
# Column width represents the byte width of each column

[layout]
offset-style = 'hex' # 'hex', 'dec', 'off'

[layout.bin]
column-count = 4
column-size  = 1

[layout.hex]
column-count = 4
column-size  = 4

[layout.utf8]
column-count = 8
column-size  = 4
