name: Pre-Release

on:
  create:
  push:
    tags:
      - v*pre

permissions:
  contents: write
  discussions: write

jobs:
  release:
    name: Create Package Pre-Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: Gr1N/setup-poetry@v8
    - run: poetry --version
    - name: Build package
      run: poetry build

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: true
        files: |
          dist/*
